ALTER TABLE passengers ADD COLUMN IF NOT EXISTS ticket_qr_token TEXT UNIQUE;
ALTER TABLE passengers ADD COLUMN IF NOT EXISTS ticket_scanned BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE passengers ADD COLUMN IF NOT EXISTS ticket_scanned_at TIMESTAMP WITH TIME ZONE;
